listen_address: 0.0.0.0:8088
web_address: http://hostname-to-bystander:8088/
db: bystander.db
max_history: 60
notifiers:
  slack-channel-one:
    type: slack
    webhook: https://hooks.slack.com/services/.../.../...
  slack-channel-two:
    type: slack
    webhook: https://hooks.slack.com/services/.../.../...
  stderr:
    type: stderr
checks:
 - type: url
   tags:
    - name: url-check
    - subsystem: external
    - environment: prod
   timeout: 5s
   url: http://example.com/bad
   num_failures_before_alerting: 1
   num_success_before_recovery: 1
   notifier: stderr
   notes: >
       free form text, perhaps to a <a href="url.txt">url</a>?
       I'm not sure if we should support something like markdown?
       for now it will just be HTML

 - type: docker
   tags:
    - name: docker-check
    - subsystem: internal
    - environment: prod
   image: docker.internal.example.com/checks/my-check:a9f2bb72f1
   command: /app/check-command -v --foo 123
   num_failures_before_alerting: 10
   num_success_before_recovery: 2
   notifier: stderr

